sudo: require
language: python

python:
  - 3.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libblas-dev
      - liblapack-dev
      - gfortran-7

install:
  - pip install scipy

script:
  - sudo rm /usr/bin/gfortran
  - sudo ln -s /usr/bin/gfortran-7 /usr/bin/gfortran
  - cmake -H. -Bbuild -DENABLE_TEST=ON  -DCMAKE_BUILD_TYPE=Debug
  - cmake --build build
  - cd build && ctest -V
  
branches:
  only:
   - master

