sudo: require
language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libblas-dev
      - liblapack-dev

before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -y gfortran      
      
script:
  - cmake -H. -Bbuild && cmake --build build
  - ./bin/main
  
branches:
  only:
   - master

