sudo: require
language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libblas-dev
      - liblapack-dev
      - gfortran-8
      
script:
  - cmake -H. -Bbuild && cmake --build build
  - ./bin/main
  
branches:
  only:
   - master

