name: FortranCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: nlescjcer/gfortranmkl:latest
    steps:
      - uses: actions/checkout@master
      - run: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST=ON && cmake --build build
      - run: cd build && ctest -V
