name: FortranCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install gfortran
      - run: sudo apt-get install gfortran
      - name: build
      - run: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST=ON && cmake --build build
      - name: test
      - run: cd build && ctest -V
