name: FortranCI

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    image: nlescjcer/gfortranmkl:latest
    steps:
      - run: |
          cd $HOME && git clone --branch master --single-branch git://github.com/NLESC-JCER/Fortran_Davidson.git
          cd Fortran_Davidson && cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST=ON && cmake --build build
          cd build && ctest -V
    
