name: FortranCI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: sudo apt-get install gfortran libblas-dev liblapack-dev
      - name: build
        run: cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST=ON && cmake --build build
      - name: test
        run: cd build && ctest -V
